# -*- coding: utf-8 -*-
"""MongoDB connecto DB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDpZEWIwxJqI57ParaX94XexcFZpn_FR
"""

import pymongo
import pandas as pd

from pymongo import MongoClient
#Check file existe
import pathlib

client = MongoClient('vietkite.com',
                     username='realestate',
                     password='Abc654321',
                     authSource='realestate',
                     authMechanism='SCRAM-SHA-1')
db = client.realestate
collection = db.realestates

# from google.colab import drive
# drive.mount('/content/drive')

"""#Check Have Data for a Province Name"""

def Check_Have_Data():
  #Get district of the city
  tinhtp="./tinh_tp_danso_matdo.csv" #(Đọc thông tin Tỉnh/TP/Quận)
  df_city = pd.read_csv(tinhtp)

  #Test if there is a province without data
  number_of_province=len(set(df_city['ProvinceName']))
  list_of_province=list(set(df_city['ProvinceName']))
  print("So tinh thanh",len(list_of_province))
  for i in range(number_of_province):
    province=list_of_province[i]
    district_df=df_city[df_city['ProvinceName']==province]
    #district_list=list(set(district_df['DistrictName']))
    test = collection.find_one({"CityName":province})
    if (test is not None):
      print(province)
      print(test)
    else:      
      print(province+"is not correct")  
    #Check_Have_Data_District(province,district_df)

def Check_Have_Data_District(cityname,district_df):
  list_of_district=list(set(district_df['DistrictName'])) #list of district of a specific city or province
  number_of_district=len(list_of_district)
  for i in range(number_of_district):
    district_name=list_of_district[i]
    #print(district_name)
    test = collection.find_one({"CityName":cityname,"DistrictName":district_name})
    if (test is not None):
      print(district_name+":OK")
      #print(test)
    else:      
      print(district_name+": Data doesn't exist")

"""#Export the CSV file - given City Name"""

def ExportToCSVFile_CityDistrict(city,district,filename):
  ##Export data to .csv file with name=district
  #Get district of the city
  
  #district="Phú Nhuận"
  #city="Hồ Chí Minh"

  if filename is "":
    filename="./"+city+"_"+district+".csv"

  file = pathlib.Path(filename)

  if file.exists():
    print(filename+" has existed")
    return

  #Verify if there is a data
  test=collection.find_one({"CityName": city,
                        "DistrictName":district
                        }
                      )
  if (test is None):
     print(city+" "+district+" is not correct") 
     return

  data = pd.DataFrame(list(collection.find({
                                "CityName": city,
                                "DistrictName":district
                                }
                            )))  
  #Output to file for testing purposes
  data.to_csv(filename,encoding='utf-8-sig')
  print('Export to CSV file '+filename)

def ExportToCSVFile_OneCity(city,filename):
  ##Export data to .csv file with name=district
  #Get district of the city
  
  #district="Phú Nhuận"
  #city="Hồ Chí Minh"

  if filename is "":
    filename="./"+city+"_"+".csv"

  file = pathlib.Path(filename)

  if file.exists():
    print(filename+" has existed")
    return

  #Verify if there is a data
  test=collection.find_one({"CityName": city,                        
                        }
                      )
  if (test is None):
     print(city+" is not correct") 
     return

  data = pd.DataFrame(list(collection.find({
                                "CityName": city,                 
                                }
                            )))  
  #Output to file for testing purposes
  data.to_csv(filename,encoding='utf-8-sig')
  print('Export to CSV file '+filename)

#Export to all csv all district of a city
def ExportToCSVFile_City_All_District(city,filename):
  #Get district of the city
  tinhtp="./tinh_tp_danso_matdo.csv" #(Đọc thông tin Tỉnh/TP/Quận)
  df_city = pd.read_csv(tinhtp)
  
  #number_of_province=len(set(df_city['ProvinceName']))
  list_of_district=list(set(df_city[df_city['ProvinceName']==city]['DistrictName'])) #list of district of a specific city or province
  number_of_district=len(list_of_district)

  #print("So tinh thanh",len(list_of_district))
  for i in range(number_of_district):
    district_name=list_of_district[i]
    ExportToCSVFile_CityDistrict(city,district_name,filename)
    #print(city,"",district_name)

# ExportToCSVFile_City_All_District
# ExportToCSVFile_City_All_District("Bà Rịa Vũng Tàu","")
#ExportToCSVFile_City_All_District("Khánh Hòa","")
#ExportToCSVFile_City_All_District("Thừa Thiên Huế","")
#ExportToCSVFile_City_All_District("Hà Nội","")
#ExportToCSVFile_City_All_District("Đắk Nông","")
#ExportToCSVFile_City_All_District("Đắk Lắk","")
#ExportToCSVFile_City_All_District("Đồng Nai","")
#ExportToCSVFile_City_All_District("Bình Dương","")
#ExportToCSVFile_City_All_District("Long An","")
#ExportToCSVFile_City_All_District("Cần Thơ","")
#ExportToCSVFile_City_All_District("Bình Thuận","")
#ExportToCSVFile_City_All_District("Kiên Giang","")
#ExportToCSVFile_City_All_District("Nghệ An","")

ExportToCSVFile_CityDistrict("Hồ Chí Minh","Phú Nhuận", "")
#ExportToCSVFile_CityDistrict("Hồ Chí Minh","Quận 5","")

Check_Have_Data()